### ISSUE TITLE
New pageControl props in SDK 3.4.0

### ISSUE THREAD

**Issue by kishba** [ellucian-developer/experience-extension-hooks#12]
SDK 3.4.0 added two new properties under `pageControl`:

- `setPageTitle`
- `setPageToolbar`

Will experience-extension-hooks need to be updated to expose these under `useExtensionControl`?

Thanks,
Brandon

**Update**
Adding link to the [SDK 3.4.0 release notes](https://resources.elluciancloud.com/bundle/ellucian_experience_rel_release_notes/page/c_rel_notes_sdk_340_enhancements.html)

**Comment by ellucianBret** [comment]
Definitely, these need to be added. 

Will do so a.s.a.p.

Bret

**Comment by ellucianBret** [comment]
Fixed with #13
