### ISSUE TITLE
Error building: Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by kishba** [ellucian-developer/experience-extension-hooks#2]
I tried adding this hooks project to a new extension. When I start the project or `npm run build-dev` I get the following error:

```
ERROR in ./node_modules/@ellucian/experience-extension-hooks/src/components/extension-context.js 75:8
Module parse failed: Unexpected token (75:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|     return (
>         <ExtensionContext.Provider value = { contextValue } >
|             { children }
|         </ExtensionContext.Provider>
 @ ./node_modules/@ellucian/experience-extension-hooks/index.js 1:0-11:44 1:0-11:44 1:0-11:44 1:0-11:44 1:0-11:44 1:0-11:44 1:0-11:44 1:0-11:44 1:0-11:44 1:0-11:44
 @ ./src/cards/CacheCard.jsx 10:0-73 112:42-59
```

This is with an existing extension as well as with a brand new extension generated with this command:

```bash
npx -p https://cdn.elluciancloud.com/assets/SDK/latest/ellucian-create-experience-extension-latest.tgz create-experience-extension name-of-extension
```

Since I don't have the `@ellucian` package registry, I installed this package from GitHub:

```bash
npm install https://github.com/ellucian-developer/experience-extension-hooks
```

The bottom of my `CacheCard.jsx` looks like this:

```jsx
function CardOrPageWithProviders(props) {
    return (
        <ExtensionProvider {...props}>
            <CacheCard/>
        </ExtensionProvider>
    )
}

export default withIntl(withStyles(styles)(CardOrPageWithProviders));
```

Any ideas what I might need to change to get this to build? :)

**Comment by ellucianBret** [comment]
Brandon,

You need this block in your webpack.config.js in the "//For advanced scenarios" - I will add this to the docs

```
// this is needed for @ellucian/experience-extension-hooks
    webpackConfig.module.rules.forEach( rule => {
        if (rule.loader === 'babel-loader' || rule.loader === 'eslit-loader') {
            rule.exclude = /node_modules\/(?!(@ellucian)\/)/
        }
    })
```

See https://github.com/ellucian-developer/experience-productivity-extensions/blob/main/google-webpack.config.js#L33

**Comment by kishba** [comment]
Is “es-lit” a typo?

**Comment by ellucianBret** [comment]
Looks like it. Now questioning why it is there at all. I think all that is needed is the babel-loader check

**Comment by ellucianBret** [comment]
I added a note in the installation part of the readme.

@kishba does this work for you now?

**Comment by kishba** [comment]
It wasn't working until I did one more thing.

I copied the `babel.config.js` file from the productivity cards repo to our extension repo. I confirmed `babel.config.js` isn't created by the npx `create-experience-extension` command. Is that worth noting in the readme, too?

**Comment by ellucianBret** [comment]
@kishba - that reminds me. I think create-experience-extension creates a .babelrc and that didn't seem to get loaded until I changed the file name to babel.config.js. I have not figured out why yet.

Thanks for this feedback

**Comment by ellucianBret** [comment]
Updating the npm install in readme.md too :)

**Comment by ellucianBret** [comment]
Readme was updated to resolve these issues
