### ISSUE TITLE
Question: Is there a better way to get extension-wide configuration in a way that works on both cards and pages?

### ISSUE THREAD

**Issue by kishba** [ellucian-developer/experience-extension-hooks#5]
I'm trying to write sub-components and hooks that can be used the same way between cards and pages. One potential use case is our "Wait List" card that we want to include on our "Registration" page without duplicating code.

This hooks project has already facilitated a lot of what we want to do, but we ran into an issue trying to access our extension-wide URL configuration values. 

Below is our current workaround which feels a little cumbersome. Is there something in this hooks project that would make this unnecessary? Or could you recommend a more simple way to get configuration?

```javascript
  // useExtensionInfo.configuration will only be defined on pages
  // don't let the awesomeness of useExtensionControl in the readme lead to assumptions about useExtensionInfo() :)
  // https://github.com/ellucian-developer/experience-extension-hooks
  const { configuration: extensionConfiguration } = useExtensionInfo();
  const { configuration: cardConfiguration } = useCardInfo();
  const configuration =
    typeof extensionConfiguration === "undefined"
      ? cardConfiguration
      : extensionConfiguration;

  const selfServiceBaseURL =
    configuration?.extensionSelfServiceBaseURL ||
    "https://self-service.schoolcraft.edu/Student";
```

**Comment by ellucianBret** [comment]
The dilemma is Experience sends cards both card and extension level configuration in cardInfo.cardConfiguration and pages send cardConfiguration in cardInfo.cardConfiguration and extension configuration in extensionInfo.configuration.

As you know, I was involved in both choices and I have a different take on them now LOL.

To not break this for existing uses, how about if I add a cardConfiguration and extensionConfiguration to useExtensionInfo. Then regardless of the component type, you can use the appropriate configuration on extensionConfiguration.

Wait, looking at your code it isn't clear what configuration you are trying to access. Card level configuration is always available in useCardInfo. You may have missed that. I committed a change 2 days ago that yielded this. See version 1.0.1.

I am betting that you can always just use useCardInfo(). This contains the combined card level and extension level configuration.

**Comment by kishba** [comment]
I think I tried with your change from 2 days ago, but I'll try again.

I'm trying to access an extension-wide configuration value. If I try `useCardInfo` when I'm on a page, will it have the extension-wide configuration values? I think I observed otherwise, but I may be misremembering.

Reviewing my sample code, I do see I'm likely losing some configuration values when both extension-wide and card-specific configuration values exist on pages.

**Comment by ellucianBret** [comment]
There is a bug that will be fixed soon. If you have or ever have set an extension level configuration and later attempt to use that same key as a card level configuration, the extension level value will shadow the card level.

I recommend using a naming convention that prevents shadowing card level by extension level.

**Comment by ellucianBret** [comment]
I just tested. You are correct. In a Page useCardInfo.cardConfiguration does not have the extension level configuration. 

I will make a mod so that your code will be easier. That is the whole point of this thing!

**Comment by kishba** [comment]
Thank you! I have a feeling I know where you're going with this improvement, and on my side of things, I think I'll be using something more akin to this (rather than trying to establish a single `configuration` variable):

```javascript
const selfServiceBaseURL =
    extensionConfiguration?.extensionSelfServiceBaseURL ||
    cardConfiguration?.extensionSelfServiceBaseURL ||
    "https://self-service.schoolcraft.edu/Student";
```

---

PS I just realized I am following your naming convention suggestion! I must have been bitten by this without realizing it. :joy:

```javascript
module.exports = {
  name: "schoolcraft-playground",
  publisher: "bkish",
  configuration: {
    client: [
      {
        key: "extensionSelfServiceBaseURL",
        label: "Extension: Self-Service base URL",
        type: "string", // not url, because we want to allow non-https values
        required: false
      },
...
```

**Comment by ellucianBret** [comment]
Closed with https://github.com/ellucian-developer/experience-extension-hooks/pull/6
